Repository bowseruk/screen-test, pull requests merged in 2023-02, with the labels that each got.

#4 added boilerplate files
  assets/css/style.css
  assets/js/script.js
  index.html
Labels: enhancement

#20 adding pseudocode before we start coding
  pseudocode.txt
Labels: documentation, enhancement

#33 Added favicons based on logo
  assets/images/logo-animate.ico
  assets/images/logo-closed.ico
  assets/images/logo-open.ico
Labels: enhancement

#38 Added credits to the readme
  README.md
Labels: documentation

#52 Add logo
  assets/css/style.css
  assets/images/Screen Time Logo Closed Outline.png
  assets/images/Screen Time Logo Closed Shadow.png
  assets/images/Screen Time Logo Closed.png
  assets/images/Screen Time Logo Opened Outline.png
  assets/images/Screen Time Logo Opened Shadow.png
  assets/images/Screen Time Logo Opened.png
  assets/images/popcorn.png
  assets/js/script.js
  assets/js/view.js
  index.html
Labels: enhancement

#64 Make current name show in modal
  assets/js/controller.js
Labels: enhancement

#63 Curtains
  assets/images/screenshot.png
  assets/js/controller.js
  assets/js/view.js
  index.html
Labels: documentation, enhancement
